[package]
name = "tutorlolv2_frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = { version = "2.0.1", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
reqwasm = { version = "0.5.0", default-features = false, features = ["http"] }
synoptic = "2.2.9"
yew = { version = "0.21.0", features = ["csr"] }
yew-router = "0.18.0"
rustc-hash = "2.1.1"
once_cell = "1.21.3"
web-sys = "0.3.77"
wasm-bindgen = "0.2.100"
